### ISSUE TITLE
Add exclusions via front-matter or in code-blocks

### ISSUE THREAD

**Issue by djw4** [aleen42/gitbook-treeview#7] opened 2018-10-16 00:00 UTC
Is it/would it be possible to exclude generation of tree view on some pages - perhaps via front-matter? Alternatively (perhaps easier) can it skip generation of tags within code blocks?

It works great on most of my pages, but I have a collection of some scripts in my docs, and it's interpreting the bash comments as headers, so it generates the following:

```
* !/bin/bash
* lookup name servers at the registrar
* - - - - - - - - - - - - - # Check for input
* - - - - - - - - - - - - - if [ -z "$1" ]
* - - - - - - - - - - - - - # Generate input
* - - - - - - - - - - - - - if [ -f "/var/cpanel/cpanel.config" ]
* - - - - - - - - - - - - - # Start operations
* - - - - - - - - - - - - - for i in $domains; do
```

My comments look like the following:

```
# lookup name servers at the registrar
..
# - - - - - - - - - - - - - # Start operations
..
etc
```

**Comment by aleen42** [comment] 2018-10-16 00:41
For more information, I would like to know whether your bash comments are wrapped within a code block?  Like the following case:

```bash
# comments
```

I will try to reproduce the problem later.

**Comment by aleen42** [comment] 2018-10-16 03:01
Since `gitbook-treeview@2.4.4`, I have fixed the bug within code blocks, and you can try the latest version of this plugin @djw4.

**Comment by aleen42** [comment] 2019-07-31 06:01
I am going to close this issue if there is no problems, just feel free to reopen it.

**Closed as completed by aleen42** 2019-07-31 06:01 UTC
